timeout: 600s
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/sample-api/main', '.']
images:
  - 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/sample-api/main'
options:
  logging: CLOUD_LOGGING_ONLY