on:
  workflow_dispatch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "times-sys-cat"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "GithubAction実施"
          SLACK_MESSAGE: "${{ github.ref_name }} でのGithubAction実施"