on:
  workflow_dispatch

jobs:
  notify:
    runs-on: ubuntu-latest

    env:
      TARGET_BRANCH: ${{github.ref_name}}
      TAG_BRANCH: ""
    steps:
      - id: transform_branch
        run: echo "transformed_branch=${TARGET_BRANCH//\//_}" >> $GITHUB_ENV
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "times-sys-cat"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "GithubAction実施"
          SLACK_MESSAGE: "${{ env.transformed_branch }} でのGithubAction実施"
      - run: echo "End"